library(lubridate)
library(dplyr)
library(reshape2)
library(hyfo)
library(ggplot2)
library(stringr)
scen = "MIROC5_rcp85"
rm(list=ls(all=TRUE)) #start with empty workspace
p <- paste("C:/Users/Aditya/Box Sync/VICE Lab/RESEARCH/PROJECTS/CERC-WET/Task7_San_Joaquin_Model/Pywr models/data/San Joaquin River/Scenarios/",scen,"/preprocessed", sep = '')
df <- read.csv(paste(p,'/full_natural_flow_daily_mcm.csv', sep = ''))
df$Date <- as.Date(mdy(df$Date))
df$Year <- year(df$Date)
df$Month <- month(df$Date)
print(head(df))
df_TF <- df %>% group_by(Year) %>% filter(Month %in% c(4,5,6,7))
df_TF2 <- aggregate(df_TF[,2],by=list(df_TF$Year),FUN=sum,na.rm=TRUE)
colnames(df_TF2) <- c("Year","Flow")
df_TF2$Flow <- df_TF2$Flow*70.05 #cms to AF/day
print(head(df_TF2))
write.csv(df_TF2,file=paste(p,"/inflow_MillertonLake_AprToJul_AF.csv", sep=""), row.names = FALSE)